---
- name: Install Docker and Rancher on Ubuntu
  hosts: dbtzen
  become: yes
  vars:
    rancher_version: v2.9.0
    docker_timeout: 300
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
    
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull Rancher image
      docker_image:
        name: "rancher/rancher:{{ rancher_version }}"
        source: pull
      async: "{{ docker_timeout }}"
      poll: 5

    - name: Install Rancher
      docker_container:
        name: rancher
        image: "rancher/rancher:{{ rancher_version }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /opt/rancher:/var/lib/rancher
      async: "{{ docker_timeout }}"
      poll: 5

    - name: Wait for Rancher to be ready
      uri:
        url: "https://{{ ansible_host }}"
        validate_certs: no
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 10
