---
- name: Install Docker and Setup Rancher with Docker Compose on Ubuntu
  hosts: dbtzen
  become: yes
  vars:
    rancher_version: latest
    docker_timeout: 300
  tasks:
    - name: Install Docker using snap
      community.general.snap:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: snap.docker.dockerd
        state: started
        enabled: yes

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create directory for Rancher
      file:
        path: /opt/rancher
        state: directory
        mode: '0755'

    - name: Create Docker Compose file for Rancher
      copy:
        dest: /opt/rancher/docker-compose.yml
        content: |
          version: '3'
          services:
            rancher:
              image: "rancher/rancher:{{ rancher_version }}"
              restart: always
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - rancher-data:/var/lib/rancher
              privileged: true
          volumes:
            rancher-data:

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start Rancher with Docker Compose
      command: docker-compose -f /opt/rancher/docker-compose.yml up -d
      args:
        chdir: /opt/rancher
      async: "{{ docker_timeout }}"
      poll: 5

    - name: Wait for Rancher to be ready
      uri:
        url: "https://{{ ansible_host }}"
        validate_certs: no
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 10
